import inspect
from pprint import pprint  # noqa: F401
from typing import Any, get_args

TYPE_MAP = {
    str: "string",
    int: "integer",
    float: "number",
    bool: "boolean",
    type(None): "null",
}


def get_json_type(python_type):
    if python_type in TYPE_MAP:
        return TYPE_MAP[python_type]
    
    args = get_args(python_type)
    
    if args:
        return [TYPE_MAP[arg] for arg in args]
    
    raise TypeError(f"Type non supporté : {python_type}")

def build(funcs):
    if not type(funcs) is list:
        funcs = [funcs]
    
    result: list = []
    for func in funcs:
        signature = inspect.signature(func)
        
        properties = {}
        required = []
        
        for name, param in signature.parameters.items():
            python_type = param.annotation
            
            properties[name] = {
                "type": get_json_type(python_type)
            }
            
            if param.default is inspect.Parameter.empty:
                required.append(name)
        
        result.append({
            "type": "function",
            "function": {
                "name": func.__name__,
                "description": func.__doc__ or "",
                "parameters": {
                    "type": "object",
                    "properties": properties,
                    "required": required,
                },
            },
        })
    return result

import inspect  # noqa: F811

from pydantic import TypeAdapter


def build_v2(funcs):
    funcs = funcs if isinstance(funcs, list) else [funcs]
    return [
        {
            "type": "function",
            "function": {
                "name": func.__name__,
                "description": inspect.getdoc(func) or "",
                "parameters": {
                    "type": "object",
                    "properties": {
                        name: TypeAdapter(param.annotation).json_schema(union_format="primitive_type_array")
                        for name, param in inspect.signature(func).parameters.items()
                    },
                    "required": [
                        name
                        for name, param in inspect.signature(func).parameters.items()
                        if param.default is inspect.Parameter.empty
                    ],
                },
            },
        }
        for func in funcs
    ]


class add:
    def __init__(self):
        self.result = ""
    def __call__(self, *args) -> None:
        for i in args:
            self.result += f"\n{i}"

from datetime import datetime


def get_time():
    """
    Provides the user's local time and other time-related information.
    """
    return datetime.now().astimezone()

from pathlib import Path


def ls(path: str):
    """
    Lists all items contained in the specified directory.
    """
    return [str(i) for i in list(Path(path).glob("*"))]

def cat(file: str, limit: int = 2048):
    """
    Displays the contents of the requested file.
    - limit:
             limited to the first 2048 characters by default.
             max : 8192
    """
    value = 8192
    with open(file, "r", encoding="utf-8") as f:
        return f"#file : {file}\n{f.read(max(1, min(value, limit)))}"

import subprocess


def execute(commande: str):
    """
    permet d'exécuter une commande dans un terminal Bash.
    Avant l'action, demander l'autorisation de l'utilisateur pour exécuter la commande.
    Et une autorisation supplémentaire sera également demandée à l'utilisateur.
    """
    print("\n")
    print("\033[41m" + repr(commande) + "\033[0m")
    print("\n" + "\033[41m" + "Allow the execution of this command generated by the agent?" + "\033[0m")
    
    if input("yes\\no >") == "yes":
        rs = subprocess.run(
            commande,
            shell=True,
            capture_output=True,
            text=True,
            check=False
            )
        return f"stdout : {rs.stdout}, stderr : {rs.stderr}, returncode : {rs.returncode}"
    else:
        return "The user refused the execution request."



import paramiko

ssh_objet: paramiko.SSHClient | None = None

def ssh_login(ip: str, port: int, username: str, password: str, key_filename: str|None = None):
    """
    Creates a persistent SSH connection.
    """
    global ssh_objet
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    
    ssh.connect(
        hostname=ip,
        port=port,
        username=username,
        password=password,
        key_filename=key_filename,
        timeout=10
    )
    ssh_objet = ssh

def ssh_commande(commande: str, timeout: int = 20):
    """
    Executes the specified command on the SSH session previously created by ssh_login.
    - timeout:
               Maximum timeout: 300 seconds
               Default timeout: 20 seconds
    """
    if ssh_objet is None:
        return "No SSH connection was created beforehand; use 'ssh_login'."
    
    stdin, stdout, stderr = ssh_objet.exec_command(commande, timeout=min(300, timeout))  # noqa: RUF059
    
    return f"stdout : {stdout.read().decode()}, error : {stderr.read().decode()}, returncode : {stdout.channel.recv_exit_status()}"


import os
from pathlib import Path  # noqa: F811

BASE = (Path.home() / "Documents" / "enboite-share" / "share").resolve()
os.makedirs(BASE, exist_ok=True)

def ssh_tranfer_client2hote(file_source: str, file_hote: str):
    """
    Allows transferring a file (files only) from the SSH connection to the user's machine.
    The tool only accepts relative file paths.
    """
    if ssh_objet is None:
        return "No SSH connection was created beforehand."
    
    if Path(file_hote).is_absolute():
        raise ValueError("Absolute path prohibited")
    
    path = (BASE / file_hote).resolve()
    if not path.is_relative_to(BASE):
        raise ValueError("Path traversal forbidden")
    
    ssh_objet.open_sftp().get(
        file_source,
        path
    )
    return f"True, file hote is : {path}"

def ssh_close():
    """
    Close the previously established connection.
    """
    global ssh_objet
    if ssh_objet is None:
        return "No SSH connection was created beforehand."
    
    ssh_objet.close()
    ssh_objet = None
    return True

from notifypy import Notify


def notify(title: str, message: str):
    """
    Sends a desktop notification to the user's operating system.
    The notification is displayed by the user's desktop environment.
    """
    notification = Notify()
    notification.title = title
    notification.message = message
    notification.send()
    return True


import platform

import cpuinfo
import distro
import psutil
from screeninfo import get_monitors


def system():
    """
    Provides a comprehensive report of system information,
    including the operating system, hardware, and other available details.
    
    Available information: display, OS, CPU, RAM, storage, etc.
    """
    _ = add()
    _("=== OS ===")
    _("Système :", platform.system())
    _("Distribution :", distro.name())
    _("Version :", distro.version())
    _("Kernel :", platform.release())
    _("Architecture :", platform.machine())
    _("\n=== CPU ===")
    _("CPU :", cpuinfo.get_cpu_info().get("brand_raw"))
    _("Ceurs physiques :", psutil.cpu_count(logical=False))
    _("Threads :", psutil.cpu_count(logical=True))
    _("\n=== RAM ===")
    ram = psutil.virtual_memory()
    _("Total :", round(ram.total / 1024**3, 2), "GB")
    _("Utilisée :", round(ram.used / 1024**3, 2), "GB")
    _("\n=== DISQUES ===")
    for partition in psutil.disk_partitions():
        try:
            usage = psutil.disk_usage(partition.mountpoint)
            _(
                partition.device,
                partition.mountpoint,
                f"{usage.total / 1024**3:.1f} GB"
            )
        except PermissionError:
            pass
    
    _("\n=== ÉCRANS ===")
    for monitor in get_monitors():
        _(
            monitor.name,
            f"{monitor.width}x{monitor.height}",
            f"@ ({monitor.x}, {monitor.y})"
        )
    return _.result


import socket

import requests


def get_ip():
    """
    permet d'avoir l'ip local utilisé pour les connexion, et l'ip publique
    """
    def get_ip(url: str) -> str | None:
        try:
            r = requests.get(url, timeout=3)
            r.raise_for_status()
            return r.text.strip()
        except requests.RequestException as e:
            return f"error : '''{e}'''"
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80))
    ip = s.getsockname()[0]
    s.close()
    return f"local : {ip}, public_IPv4 : {get_ip("https://api.ipify.org")}, public_IPv6 : {get_ip("https://api6.ipify.org")}"

import geoip2.database


def get_geo_ip(ip: str):
    """
    Provides geolocation information for an IP address using GeoLite2-City,
    including the geographic coordinates (latitude and longitude).
    """
    with geoip2.database.Reader("GeoLite2-City.mmdb") as reader:
        _ = add()
        response = reader.city(ip)
        #pprint(response, depth=None)
        _("continent: ", response.continent.name)
        _("country: ", response.country.name)
        _("subdivisions: ", ", ".join([i.name for i in response.subdivisions]))
        _("city: ", response.city.name)
        _("city_postal: ", response.postal.code)
        _("latitude: ", response.location.latitude)
        _("longitude: ", response.location.longitude)
        return _.result

from ddgs import DDGS


def search_web(query: str, max_results: int = 5):
    """
    permet une recherche web,
    retourne un enssemble de réponses.
    recu : URL, titre, courte description
    
    - max_results:
        spécifier le nombre de résultat. defaut 5, max 15, min 1.
    """
    max_result = 15
    
    _ = add()
    return "\n\n".join(
        f"Titre : {r['title']}\n"
        f"URL : {r['href']}\n"
        f"Description : {r['body']}"
        for r in DDGS().text(query, max_results=max(1, min(max_result, max_results)))
    )


def fetch_url_v1(url: str):
    """
    retourne le contenue d'une page.
    format : markdown
    """
    return DDGS().extract(
        url,
        fmt="text_markdown",
    )["content"]

def fetch_url_raw_v1(url: str, proxy: str|None = None):
    """
    retourne le contenue d'une page.
    format : html/raw
    
    - proxy:
            - exmanples:
                        "socks5h://127.0.0.1:9050"
    """
    
    kwargs = {}
    
    if proxy:
        kwargs["proxies"] = {
            "http": proxy,
            "https": proxy,
        }
    
    # pyrefly: ignore [bad-argument-type]
    return requests.get(url, **kwargs).text

import secrets

import docker
import docker.errors
import docker.models.containers
import docker.types

DOCKER_CONTAINER_MAX:int = 1
DOCKER_CONTAINER_LIST:list[docker.models.containers.Container] = []
DOCKER_CONTAINER_PULL: bool = False


def container_start(
    image: str|None = None,
    gpus: list[int]|int|None = None
) -> str:
    """
    Creates a container on the user's machine.
    The container includes an SSH server.
    The command returns all the information required to establish an SSH connection.
    It also exposes a range of ports, allowing the user to connect to ports inside the container.
    
    All data in the container will be deleted when it is stopped.
    The container will remain running until it is explicitly stopped by command.
    Multiple containers can be created.
    
    - image: specify the base container image,
             leave unset to automatically select a suitable base image.
             Only Debian-based images are supported.
    
    - gpus: specify the GPU IDs to attach to the container,
            use -1 to attach all GPUs,
            leave unset to attach no GPUs.
            - exmanples:
                        gpus=-1, gpus=[0,1]
    """
    # global DOCKER_CONTAINER_LIST
    if len(DOCKER_CONTAINER_LIST) >= DOCKER_CONTAINER_MAX:
        return "Maximum number of containers reached"
    
    ports_len = 5
    base = "debian:13"
    
    image = image if image else base
    
    pswd = secrets.token_hex(32)
    name = f"enboite-{secrets.token_hex(16)}"
    
    with open("enboite.container.bootstrap.sh", "r", encoding="utf-8") as f:
        bootstrap = f.read()
    
    device_request_kwargs: Any = {
        "capabilities": [["gpu"]],
    }
    
    if gpus == -1:
        device_request_kwargs["count"] = -1
    elif gpus is not None and type(gpus) is list:
        device_request_kwargs["device_ids"] = [str(i) for i in gpus]
    elif gpus is None:
        pass
    else:
        raise RuntimeError("inlid argument for 'gpus'")
    
    client = None
    try:
        client = docker.from_env()
        
        try:
            client.images.get(image)
        except docker.errors.ImageNotFound:
            if DOCKER_CONTAINER_PULL:
                client.images.pull(image)
            else:
                return "Image Not Found, pull deactivate"
        
        container = client.containers.create(
            auto_remove=True,
            image=image,
            name=name,
            command="sleep infinity",
            ports = {
                "22/tcp": None,
                **{f"{port}/tcp": None for port in range(1024, 1024+ports_len)},
            },
            device_requests=[
                docker.types.DeviceRequest(
                    **device_request_kwargs
                )
            ],
        )
        DOCKER_CONTAINER_LIST.append(container)
        
        container.start()
        
        container.reload()
        
        result = container.exec_run(
            ["bash", "-e", "-c", bootstrap],
            environment={
                "bootstrap_password_root": pswd
            },
            stream=False
        )
        
        if result.exit_code != 0:
            # pyrefly: ignore [missing-attribute]
            raise RuntimeError(f"error in the bootstrap container : code {result.exit_code}, output : {result.output.decode("utf-8", errors="replace")}")
        
        # pyrefly: ignore [unsupported-operation]
        return f"True\nusername : {"root"!r},\npassword : {pswd!r},\nip : {'localhost'!r},\nport(s) :\n  " + "\n  ".join(f"port container : {i} > host port {z[0]["HostPort"]}" for i, z in container.ports.items())
    finally:
        if client:
            client.close()

def container_images():
    """
    Return the list of Docker images that are already pulled and available locally.
    """
    client = None
    try:
        client = docker.from_env()
        
        images = client.images.list()
        
        return "\n".join([tag for image in images for tag in image.tags])
    finally:
        if client:
            client.close()

import base64
from io import BytesIO

import mss
from PIL import Image


def screenshot(monitors_index: list[int]) -> dict[str, list[str] | str]:
    """
    Review the screenshots for all specified IDs.
    Use 'system' to retrieve the total number of screenshots.
    """
    sct = mss.mss()
    results = []
    
    for id in monitors_index:
        id += 1
        shot = sct.grab(sct.monitors[id])
        image = Image.frombytes("RGB", shot.size, shot.rgb)
        buffer = BytesIO()
        image.save(buffer, format="PNG")
        results.append(base64.b64encode(buffer.getvalue()).decode("ascii"))
    return {"type": "images", "value": results}

def read_media(file: str):
    """
    Allows the LLM to receive and visually analyze an image.
    The image is directly added to the conversation so that you can see and understand its content.
    Supported formats: JPG, JPEG, PNG. Other formats may work but are not guaranteed.
    """
    if not os.path.isfile(file):
        return 'no found the spécied input file path'
    
    with open(file, "rb") as f:
        return {"type": "images", "value": [base64.b64encode(f.read()).decode("ascii")]}


def test(value: list[tuple[int, int]]):
    """
    ne pas utilisé.
    sert a rien.
    """
if __name__ == "__main__":
    pass